<?php

const HTTP_SUCCESS = 200;
const HTTP_CREATED = 201;
const HTTP_ACCEPTED = 202;
const HTTP_NO_CONTENT = 204;

const HTTP_BAD_REQUEST = 400;
const HTTP_UNAUTHENTICATED = 401;
const HTTP_PAYMENT_NEEDED = 402;
const HTTP_FORBIDDEN = 403;
const HTTP_NOT_FOUND = 404;
const HTTP_METHOD_NOT_ALLOWED = 405;
const HTTP_VALIDATION_ERROR = 422;
const HTTP_TOO_MANY_REQUESTS = 429;

const HTTP_SERVER_ERROR = 500;
const HTTP_SERVICE_UNAVAILABLE = 503;
